version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstall.sh
      runas: ubuntu
      timeout: 300
