name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Build
        run: yarn build

      - name: zip
        run: zip -r ${{ github.sha }}.zip dist package.json yarn.lock .platform Procfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://${{ secrets.AWS_BUCKET }}/${{ github.ref_name }}/${{ github.sha }}.zip --region ${{ secrets.AWS_REGION }}

      - name: Deploy elasticbeanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.AWS_EB_APPLICATION }} --version-label ${{ github.sha }} --source-bundle S3Bucket=${{ secrets.AWS_BUCKET }},S3Key=${{ github.ref_name }}/${{ github.sha }}.zip --region ${{ secrets.AWS_REGION }}
          aws elasticbeanstalk update-environment --environment-name ${{ secrets.AWS_EB_ENVIRONMENT }} --version-label ${{ github.sha }} --region ${{ secrets.AWS_REGION }}
